### PR TITLE
Init state in blob storage via terraform

### PR DESCRIPTION
**Pull request by mud5150**
So we actually ended up doing more that we intended in this pull request. But it's all good stuff and I have it running on our TFS server with fantastic success. :)

* We [added some default parameters](https://github.com/mud5150/Xpirit-Vsts-Release-Terraform/issues/4) that are included on every run.
* We updated to [use the built in support for Azure remote backend](https://github.com/mud5150/Xpirit-Vsts-Release-Terraform/issues/2). This allowed for:
    * [Using remote backend options from a .tf file](https://github.com/mud5150/Xpirit-Vsts-Release-Terraform/issues/3)
    * Or using values provided in the build step to [select the storage account](https://github.com/mud5150/Xpirit-Vsts-Release-Terraform/commit/5f4d386b73ff1c715932a224774ba145a17592c9)

Let me know if you see any issues. Thanks for being so responsive btw.

### CODE REVIEW

**Comment by mud5150** [comment]
@pgroene Thanks for getting this pushed out to the marketplace. Since I can't respond to questions there I tracked down the person on linkedIn who left the recent question about the workflow and having issues. I'll try to see if there's anything I broke or missed with those updates.

**Comment by pgroene** [comment]
@mud5150 i'll try to get your latest updates published today in a preview version

**Comment by pgroene** [comment]
@mud5150  I have create a 2.0.0 version, are you able to verify that it is working as intended before I upload it and break all users? I do only have limited time to do verification. If you need some help you can contact me directly, pgroene@gmail.com.

[petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform-2.0.0.vsix.zip](https://github.com/XpiritBV/Xpirit-Vsts-Release-Terraform/files/1874621/petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform-2.0.0.vsix.zip)

**Comment by mud5150** [comment]
@pgroene Ah, I see. The screenshot in the marketplace was updated so I thought you already published the changes. Yes, from my standpoint everything is working great. I uploaded it to our tfs server with the cli tool before I put in the pull request and we've had it running on a bunch of our builds since then. Thanks!

**Pull request merged**
